In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
import pandas_profiling


In [ ]:
test = pd.Series(range(5))
test[2] = np.nan
test
test.cumsum(skipna=)

In [ ]:
df = pd.read_csv("train.csv")
df

In [ ]:
df


In [ ]:
df.info()

In [ ]:
df.shape


In [ ]:
# df.isnull().sum()
df.describe()

In [ ]:
# plt.subplots(figsize=(20,15))
ax = plt.axes()
ax.set_title("Correlation Heatmap")
corr = df.corr()
sns.heatmap(corr, annot=True,
            xticklabels=corr.columns.values,
            yticklabels=corr.columns.values)

In [ ]:
report = pandas_profiling.ProfileReport(df)
report.to_file(outputfile="myoutput.html")


In [ ]:
import sweetviz as sv

#Generating Sweetviz report
report = sv.analyze(df)
report.show_html("sv_report.html")  # specify a name for the report

In [ ]:
from autoviz.AutoViz_Class import AutoViz_Class

AV = AutoViz_Class()
filename = "train.csv"  # empty string ("") as filename since no file is being used for the data
sep = ","
dft = AV.AutoViz(
    '',
    sep=",",
    depVar="",
    dfte=df,
    header=0,
    verbose=0,
    lowess=False,
    chart_format="svg",
    max_rows_analyzed=150000,
    max_cols_analyzed=30,
)
% matplotlib inline
dft
# _ = AV.AutoViz(filename)


In [ ]:
import dtale

dtale.show(df, open_browser=True)

In [ ]:
from dataprep.datasets import load_dataset
from dataprep.eda import create_report
from dataprep.eda import plot, plot_correlation, plot_missing

report = create_report(df)
report

In [ ]:
plot(df)

In [ ]:
df.isnull().sum()

In [ ]:
df.sum(axis='columns')

In [ ]:
df[df['HomePlanet'].notna()]

In [ ]:

df[df.loc[:, ['HomePlanet', 'CryoSleep']].isna().T.any()]

In [ ]:
df['HomePlanet'].isna()

In [ ]:
df.isnull().any()

In [ ]:
df

In [ ]:
df.loc[:, ['HomePlanet', 'CryoSleep']].duplicated()

In [ ]:
c = {'Earth': 'yes', 'Europa': 'no', "Mars": 'ok', np.nan: 'fuck'}

In [ ]:
df['test'] = df['HomePlanet'].map(lambda x: c[x])
df

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins, right=False)
cats

In [ ]:
data = np.random.randn(1000)
cats = pd.cut(data, 4)
s = pd.Series(cats)
s.value_counts()

In [ ]:
df['RoomService'].dtype

In [ ]:
df

In [ ]:
df['RoomService'] == 0

# df.loc[df['RoomService']==0, 'RoomService']
df.loc[(df['RoomService'] == 0) & (df['VIP'] == False), ['RoomService', 'VIP']]

In [ ]:
df

In [ ]:
df

In [ ]:
dummies = pd.get_dummies(df['CryoSleep'], prefix='Sleep')
dummies

In [ ]:
df_with_dummy = df.join(dummies)  # 在原数据集上加上新列
df_with_dummy

In [ ]:
import random

pd.Series(np.random.randint(10, 100, df.shape[0])).values


In [ ]:
pd.Series(np.random.randint(10, 100, df.shape[0]))


In [ ]:
df[df['HomePlanet'].isnull()]

In [ ]:
df.iloc[[1, 2, 3], :]

In [ ]:
df

In [ ]:
df[['HomePlanet', 'Cabin']]

In [ ]:
df.shape

In [ ]:
df.isnull().T.any()

In [ ]:
df.isnull().sum()

In [ ]:
import lux
import pandas as pd

In [ ]:
df

In [ ]:
from pycaret.classification import *

s = setup(df, target='Transported')

In [ ]:
from pycaret.datasets import get_data

data = get_data('diabetes')

In [ ]:
from pycaret.classification import *

s = setup(data, target='Class variable')

In [ ]:
best = compare_models()

In [ ]:
from category_encoders import *
import pandas as pd
from sklearn.datasets import load_boston

bunch = load_boston()
y = bunch.target
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
enc = TargetEncoder(cols=['CHAS', 'RAD']).fit(X, y)
numeric_dataset = enc.transform(X)
print(numeric_dataset.info())

In [ ]:
bunch.target

In [ ]:
numeric_dataset.RAD.value_counts()

In [ ]:
X.RAD.value_counts()

In [ ]:
import category_encoders as ce
import pandas as pd

#Create the dataframe
data = pd.DataFrame(
    {'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Delhi', 'Hyderabad', 'Mumbai', 'Agra']})

#Create an object for Base N Encoding
encoder = ce.BaseNEncoder(cols=['city'], return_df=True, base=2)

data_encoded = encoder.fit_transform(data)
data_encoded

In [54]:
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore']})

In [163]:
from sklearn import preprocessing
import pandas as pd

df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore']})
enc = preprocessing.LabelEncoder()  #获取一个LabelEncoder

enc = enc.fit(df['city'])  #训练LabelEncoder
label = enc.transform(df['city'])  #使用训练好的LabelEncoder对原数据进行编码
enc_df = pd.DataFrame(label, columns=['city_label'])
df = df.join(enc_df)
df


city  city_label
0      Delhi           2
1     Mumbai           4
2  Hyderabad           3
3    Chennai           1
4  Bangalore           0

In [45]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Chennai']})
label_enc = preprocessing.LabelEncoder()  #获取一个LabelEncoder
label_enc = label_enc.fit(df['city'])  #训练LabelEncoder
label = label_enc.transform(df['city'])  #使用训练好的LabelEncoder对原数据进行编码
label_data = np.array(label).reshape(-1, 1)
label_data


array([[2],
       [4],
       [3],
       [1],
       [0],
       [1]])

In [49]:
ord_enc = preprocessing.OneHotEncoder()

name_list = []
for i in range(label_enc.classes_.shape[0]):
    name = f'city_{i}'
    name_list.append(name)

onehot_data = ord_enc.fit_transform(label_data)
onehot_data = onehot_data.toarray()
onehot_data
onehot_data.shape
enc_df = pd.DataFrame(onehot_data, columns=name_list)
enc_df
df = df.join(enc_df)
df


array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [171]:
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Chennai']})
city = df['city'].to_frame()
city.shape

(6, 1)

In [181]:

ord_enc = preprocessing.OrdinalEncoder()

ordinal_data = ord_enc.fit_transform(df['city'].to_frame())
# ordinal_data = ordinal_data.toarray()
enc_df = pd.DataFrame(ordinal_data, columns=['ord_data'])
new_df = df.join(enc_df)
new_df

city  ord_data
0      Delhi       2.0
1     Mumbai       4.0
2  Hyderabad       3.0
3    Chennai       1.0
4  Bangalore       0.0
5    Chennai       1.0

In [177]:
dummy_data = pd.get_dummies(df['city'], prefix='city')
new_df = df.join(dummy_data)
new_df

city  city_Bangalore  city_Chennai  city_Delhi  city_Hyderabad  \
0      Delhi               0             0           1               0   
1     Mumbai               0             0           0               0   
2  Hyderabad               0             0           0               1   
3    Chennai               0             1           0               0   
4  Bangalore               1             0           0               0   
5    Chennai               0             1           0               0   

   city_Mumbai  
0            0  
1            1  
2            0  
3            0  
4            0  
5            0

In [191]:
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Chennai']})

#Create an object for Base N Encoding
encoder = ce.BinaryEncoder(cols=['city'], return_df=True)

data_encoded = encoder.fit_transform(df['city'])
new_df = df.join(data_encoded)
new_df


city  city_0  city_1  city_2
0      Delhi       0       0       1
1     Mumbai       0       1       0
2  Hyderabad       0       1       1
3    Chennai       1       0       0
4  Bangalore       1       0       1
5    Chennai       1       0       0

In [188]:
import category_encoders as ce
import pandas as pd

#Create the dataframe
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Chennai']})

#Create an object for Base N Encoding
encoder = ce.BaseNEncoder(cols=['city'], return_df=True, base=2)

data_encoded = encoder.fit_transform(df['city'])
data_encoded

city_0  city_1  city_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1
5       1       0       0

In [220]:
import category_encoders as ce
import pandas as pd
import hashlib

df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Chennai']})

# md5 = hashlib.md5()
#Create object for hash encoder
encoder = ce.HashingEncoder(cols=['city'], hash_method='sha256', n_components=8, return_df=True)

#Fit and Transform Data
new_df = encoder.fit_transform(df)
new_df
# df = df.join(new_df)
# df

col_0  col_1  col_2
0      0      0      1
1      1      0      0
2      0      1      0
3      0      1      0
4      1      0      0
5      0      1      0

In [223]:
import category_encoders as ce

encoder = ce.CountEncoder(cols=['city'])
new_df = encoder.fit(df).transform(df)
new_df


city
0     1
1     1
2     1
3     2
4     1
5     2

In [233]:
encoder = ce.TargetEncoder(cols=['city'], verbose=False,)
new_df = encoder.fit(df).transform(df)
new_df

ValueError: Supervised encoders need a target for the fitting. The target cannot be None

In [243]:
from category_encoders import *
import pandas as pd
from sklearn.datasets import load_boston
bunch = load_boston()
# y = bunch.target
# X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
# enc = TargetEncoder(cols=['CHAS', 'RAD']).fit(X, y)
# numeric_dataset = enc.transform(X)
# X
# y
# bunch.data

/home/lucas/anaconda3/envs/ML/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California ho

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])